services:
  - type: web
    name: moneyTracker
    env: node
    branch: master
    startCommand: node .output/server/index.mjs
    buildCommand: yarn && yarn build
    envVars:
      - key: NITRO_PRESET
        value: render-com
